2020-06-01 17:50:22,897 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            97]
            
2020-06-01 18:07:33,908 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            97]
            
2020-06-01 18:19:06,151 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            97]
            
2020-06-01 21:19:51,794 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            97]
            
2020-06-01 22:30:25,720 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            97]
            
2020-06-01 22:37:02,345 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            97]
            
2020-06-01 22:41:16,183 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            97]
            
2020-06-01 22:41:37,067 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            97]
            
2020-06-01 22:42:16,964 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            97]
            
2020-06-01 22:47:53,579 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            97]
            
2020-06-01 22:49:20,906 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            97]
            
2020-06-01 22:53:17,326 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            97]
            
2020-06-01 22:53:18,856 ERROR: 
            Exception on /index/ph [GET] [in /home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py:
            1892]
            
Traceback (most recent call last):
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/lean/Arhat/app/main/routes.py", line 72, in index
    date_form=date_form,
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/jinja2/loaders.py", line 129, in load
    code = environment.compile(source, name, filename)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/lean/Arhat/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/lean/Arhat/app/templates/index.html", line 79, in template
    {{ form.single_event.label id="editSingleEventLabel"}}
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got 'id'
2020-06-01 22:53:42,663 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            97]
            
2020-06-01 22:55:07,405 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            97]
            
2020-06-01 23:47:21,728 INFO: 
            Template startup [in /home/lean/Arhat/app/__init__.py:
            97]
            
